# Generated by Django 4.1.6 on 2024-02-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('ogrn', models.IntegerField(blank=True, null=True, verbose_name='ОГРН')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('kpp', models.IntegerField(blank=True, null=True, verbose_name='КПП')),
                ('address_reg', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес юридической регистрации')),
                ('address_post', models.CharField(blank=True, max_length=200, null=True, verbose_name='почтовый адрес')),
                ('bill_num', models.IntegerField(blank=True, null=True, verbose_name='расчетный счет')),
                ('bill_corr_num', models.IntegerField(blank=True, null=True, verbose_name='корреспондентский счет')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя банка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['-title'],
            },
        ),
        migrations.AlterField(
            model_name='offerforcustomer',
            name='name_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.client', verbose_name='Клиент'),
        ),
    ]
