# Generated by Django 4.1.6 on 2024-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_item_options_rename_name_item_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerforcustomer',
            name='items',
            field=models.ManyToManyField(related_name='items', through='offer.OfferItems', to='offer.item', verbose_name='Товары / услуги'),
        ),
    ]
