# Generated by Django 4.1.6 on 2024-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_group_title_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/client/image', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(blank=True, null=True, verbose_name='инн'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='кпп'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.IntegerField(blank=True, null=True, verbose_name='огрн'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/item/image', verbose_name='изображение товара'),
        ),
    ]
