# Generated by Django 4.1.6 on 2024-04-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_client_bill_corr_num_alter_client_bill_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_purchase',
        ),
    ]
