# Generated by Django 4.1.6 on 2024-04-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0004_alter_offeritems_item_alter_offeritems_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='def-avatar.PNG', null=True, upload_to='media/profile-img/', verbose_name='аватар')),
                ('ogrn', models.CharField(blank=True, max_length=200, null=True, verbose_name='огрн')),
                ('inn', models.CharField(blank=True, max_length=200, null=True, verbose_name='инн')),
                ('kpp', models.CharField(blank=True, max_length=200, null=True, verbose_name='кпп')),
                ('address_reg', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес юридической регистрации')),
                ('address_post', models.CharField(blank=True, max_length=200, null=True, verbose_name='почтовый адрес')),
                ('bill_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='расчетный счет')),
                ('bill_corr_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='корреспондентский счет')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя банка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['user'],
            },
        ),
    ]
