# Generated by Django 4.1.6 on 2024-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО')], default='ip', max_length=20, null=True, verbose_name='тип компании'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='имя компании'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name_for_docs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='имя компании для документов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО')], default='ip', max_length=20, null=True, verbose_name='тип компании'),
        ),
    ]
