# Generated by Django 4.1.6 on 2024-04-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_client_company_type_profile_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
    ]
