# Generated by Django 4.1.6 on 2024-05-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_rename_avatar_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон организации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон'),
        ),
    ]
