# Generated by Django 4.1.6 on 2024-05-07 10:08

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_alter_item_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='items', to='offer.group', verbose_name='Категория'),
        ),
    ]
