# Generated by Django 4.1.6 on 2024-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_remove_item_group_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cat_type',
            field=models.CharField(choices=[('product', 'товар'), ('service', 'услуга')], db_index=True, default='product', max_length=20, verbose_name='тип категории: товар или услуга'),
        ),
    ]
