# Generated by Django 4.1.6 on 2024-05-14 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_group_cat_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pub_date', '-pub_time'], 'verbose_name': 'товар или услуга', 'verbose_name_plural': 'товары или услуги'},
        ),
        migrations.AddField(
            model_name='offerforcustomer',
            name='final_price',
            field=models.FloatField(default=0, verbose_name='Итого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerforcustomer',
            name='final_price_goods',
            field=models.FloatField(default=0, verbose_name='Итого оборудование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerforcustomer',
            name='final_price_works',
            field=models.FloatField(default=0, verbose_name='Итого монтажные работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offeritems',
            name='item_price_purchase',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, message='Нельзя добавить меньше 1 штук позиции')], verbose_name='закупка'),
        ),
    ]
