# Generated by Django 4.1.6 on 2024-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_alter_item_options_offerforcustomer_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritems',
            name='item_price_purchase',
            field=models.FloatField(default=0, null=True, verbose_name='закупка'),
        ),
    ]
