# Generated by Django 4.1.6 on 2024-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_alter_offeritems_item_price_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerforcustomer',
            name='final_price_goods',
        ),
        migrations.RemoveField(
            model_name='offerforcustomer',
            name='final_price_works',
        ),
    ]
