# Generated by Django 4.1.6 on 2024-05-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_remove_offerforcustomer_final_price_goods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerforcustomer',
            name='final_price',
            field=models.FloatField(null=True, verbose_name='Итого'),
        ),
    ]
