# Generated by Django 4.1.6 on 2024-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_alter_offerforcustomer_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerforcustomer',
            name='final_price_goods',
            field=models.FloatField(null=True, verbose_name='Итого оборудование'),
        ),
        migrations.AddField(
            model_name='offerforcustomer',
            name='final_price_work',
            field=models.FloatField(null=True, verbose_name='Итого работа'),
        ),
    ]
