# Generated by Django 4.1.6 on 2024-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_offerforcustomer_final_price_goods_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pub_date', '-pub_time'], 'verbose_name': 'товар/ услуга', 'verbose_name_plural': 'товары/ услуги'},
        ),
        migrations.AlterModelOptions(
            name='itemuser',
            options={'ordering': ['-pub_date', '-pub_time'], 'verbose_name': 'товар/ услуга пользовательский', 'verbose_name_plural': 'товары/ услуги пользовательские'},
        ),
        migrations.AddField(
            model_name='client',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-23 21:40:47.609906+03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/brand/image', verbose_name='лого бренда'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_type',
            field=models.CharField(choices=[('pc', 'шт.'), ('meters', 'м.'), ('kms', 'км.')], default='pc', max_length=20, null=True, verbose_name='количественная характеристика'),
        ),
    ]
