# Generated by Django 4.1.6 on 2024-07-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_alter_item_options_alter_itemuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-pub_date'], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='offeritems',
            options={'ordering': ['position'], 'verbose_name': 'количество товара в КП', 'verbose_name_plural': 'количество товаров в КП'},
        ),
        migrations.AddField(
            model_name='profile',
            name='bik',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Руководитель (подписант)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('fiz', 'Физическое лицо')], default='ip', max_length=20, null=True, verbose_name='тип компании'),
        ),
        migrations.AlterField(
            model_name='offerforcustomer',
            name='name_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='offerforcustomer',
            name='status_type',
            field=models.CharField(choices=[('in_edit', 'на редактировании'), ('in_process', 'КП отправлено'), ('in_prepayment', 'получена предоплата'), ('in_install', 'в работе'), ('in_payment', 'получена оплата'), ('denied', 'отказано')], default='in_edit', max_length=30, null=True, verbose_name='Статус КП'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.CharField(choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('fiz', 'Физическое лицо')], default='ip', max_length=20, null=True, verbose_name='тип компании'),
        ),
    ]
