# Generated by Django 4.1.6 on 2025-01-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_group_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bik',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='client',
            name='ruk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Руководитель (подписант)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_item', to='offer.brand', verbose_name='брэнд товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/item/imageuser/%Y-%m-%d/', verbose_name='изображение товара'),
        ),
    ]
