# Generated by Django 4.1.6 on 2026-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0021_client_bik_client_ruk_alter_item_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Мягкое удаление'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='слаг товара'),
        ),
    ]
