# Generated by Django 4.1.6 on 2026-01-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0023_auto_20260105_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_general',
            field=models.TextField(blank=True, null=True, verbose_name='описание обычное'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание техническое'),
        ),
    ]
