# Generated by Django 4.1.6 on 2026-01-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_item_description_general_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='слаг товара'),
        ),
    ]
