# Generated by Django 4.1.6 on 2026-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0025_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_min',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/item/imageuser_min/%Y-%m-%d/', verbose_name='миниатюра 150х150'),
        ),
    ]
