# Generated by Django 4.1.6 on 2026-07-11 13:33

from django.db import migrations, models
import offer.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0026_item_image_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=offer.models.item_upload_to, verbose_name='изображение товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_min',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=offer.models.item_min_upload_to, verbose_name='миниатюра 150х150'),
        ),
    ]
